---
- hosts: webservers
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: Lister les virtuals hosts
    command: /bin/ls /etc/apache2/sites-enabled/
    register: vhosts
  - debug: msg="{{ vhosts }}"
